# Crime dataset from Pandas Cookbook

- This data > CSV bc the latter only stores raw text
- Set index function
    - SYNTAX : dataset.set_index('COLUMN NAME')

- Get multiple rows with single date
    - SYNTAX : dataset.loc['DATE']

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plot

In [5]:
file = "/Users/brinkley97/Documents/development/tutorial-python_libraries/pandas/datasets/crime.h5"

In [6]:
def load_data(file):
    original_data = pd.read_hdf(file)
    # original_data = pd.DataFrame(file)
    copy_of_data = original_data.copy()
    return copy_of_data

In [7]:
copy_of_data = load_data(file)
copy_of_data

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,REPORTED_DATE,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,traffic-accident-dui-duid,traffic-accident,2014-06-29 02:01:00,-105.000149,39.745753,cbd,0,1
1,vehicular-eluding-no-chase,all-other-crimes,2014-06-29 01:54:00,-104.884660,39.738702,east-colfax,1,0
2,disturbing-the-peace,public-disorder,2014-06-29 02:00:00,-105.020719,39.706674,athmar-park,1,0
3,curfew,public-disorder,2014-06-29 02:18:00,-105.001552,39.769505,sunnyside,1,0
4,aggravated-assault,aggravated-assault,2014-06-29 04:17:00,-105.018557,39.679229,college-view-south-platte,1,0
...,...,...,...,...,...,...,...,...
460906,burglary-business-by-force,burglary,2017-09-13 05:48:00,-105.033840,39.762365,west-highland,1,0
460907,weapon-unlawful-discharge-of,all-other-crimes,2017-09-12 20:37:00,-105.040313,39.721264,barnum-west,1,0
460908,traf-habitual-offender,all-other-crimes,2017-09-12 16:32:00,-104.847024,39.779596,montbello,1,0
460909,criminal-mischief-other,public-disorder,2017-09-12 13:04:00,-104.949183,39.756353,skyland,1,0
460910,theft-other,larceny,2017-09-12 09:30:00,-104.985739,39.735045,capitol-hill,1,0

In [18]:
type(copy_of_data.dtypes), copy_of_data.dtypes

(pandas.core.series.Series,
 OFFENSE_TYPE_ID              category
 OFFENSE_CATEGORY_ID          category
 REPORTED_DATE          datetime64[ns]
 GEO_LON                       float64
 GEO_LAT                       float64
 NEIGHBORHOOD_ID              category
 IS_CRIME                        int64
 IS_TRAFFIC                      int64
 dtype: object)

In [19]:
type(copy_of_data.keys()), copy_of_data.keys()

(pandas.core.indexes.base.Index,
 Index(['OFFENSE_TYPE_ID', 'OFFENSE_CATEGORY_ID', 'REPORTED_DATE', 'GEO_LON',
        'GEO_LAT', 'NEIGHBORHOOD_ID', 'IS_CRIME', 'IS_TRAFFIC'],
       dtype='object'))

In [21]:
copy_of_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 460911 entries, 0 to 460910
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   OFFENSE_TYPE_ID      460911 non-null  category
 1   OFFENSE_CATEGORY_ID  460911 non-null  category
 2   REPORTED_DATE        460911 non-null  datetime64[ns]
 3   GEO_LON              457296 non-null  float64
 4   GEO_LAT              457296 non-null  float64
 5   NEIGHBORHOOD_ID      460911 non-null  category
 6   IS_CRIME             460911 non-null  int64
 7   IS_TRAFFIC           460911 non-null  int64
dtypes: category(3), datetime64[ns](1), float64(2), int64(2)
memory usage: 22.9 MB

In [22]:
reported_date_as_index = copy_of_data.set_index('REPORTED_DATE')
reported_date_as_index

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2014-06-29 02:01:00,traffic-accident-dui-duid,traffic-accident,-105.000149,39.745753,cbd,0,1
2014-06-29 01:54:00,vehicular-eluding-no-chase,all-other-crimes,-104.884660,39.738702,east-colfax,1,0
2014-06-29 02:00:00,disturbing-the-peace,public-disorder,-105.020719,39.706674,athmar-park,1,0
2014-06-29 02:18:00,curfew,public-disorder,-105.001552,39.769505,sunnyside,1,0
2014-06-29 04:17:00,aggravated-assault,aggravated-assault,-105.018557,39.679229,college-view-south-platte,1,0
...,...,...,...,...,...,...,...
2017-09-13 05:48:00,burglary-business-by-force,burglary,-105.033840,39.762365,west-highland,1,0
2017-09-12 20:37:00,weapon-unlawful-discharge-of,all-other-crimes,-105.040313,39.721264,barnum-west,1,0
2017-09-12 16:32:00,traf-habitual-offender,all-other-crimes,-104.847024,39.779596,montbello,1,0
2017-09-12 13:04:00,criminal-mischief-other,public-disorder,-104.949183,39.756353,skyland,1,0
2017-09-12 09:30:00,theft-other,larceny,-104.985739,39.735045,capitol-hill,1,0

In [23]:
reported_date_as_index.loc['2017-09-12']

,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
REPORTED_DATE,,,,,,,
2017-09-12 15:59:00,traffic-accident,traffic-accident,-104.940906,39.742085,city-park,0,1
2017-09-12 01:33:00,criminal-mischief-mtr-veh,public-disorder,-105.001564,39.749800,union-station,1,0
2017-09-12 00:37:00,theft-other,larceny,-104.954910,39.717317,cherry-creek,1,0
2017-09-12 02:45:00,theft-of-motor-vehicle,auto-theft,-105.009236,39.686194,ruby-hill,1,0
2017-09-12 04:59:00,theft-of-motor-vehicle,auto-theft,-105.039597,39.785489,regis,1,0
...,...,...,...,...,...,...,...
2017-09-12 14:00:00,forgery-poss-of-forged-inst,white-collar-crime,-104.991137,39.785432,globeville,1,0
2017-09-12 20:37:00,weapon-unlawful-discharge-of,all-other-crimes,-105.040313,39.721264,barnum-west,1,0
2017-09-12 16:32:00,traf-habitual-offender,all-other-crimes,-104.847024,39.779596,montbello,1,0
2017-09-12 13:04:00,criminal-mischief-other,public-disorder,-104.949183,39.756353,skyland,1,0
2017-09-12 09:30:00,theft-other,larceny,-104.985739,39.735045,capitol-hill,1,0

In [24]:
reported_date_as_index.groupby(year)

NameError: name 'year' is not defined